data/pb/RAINMAKER-PGR/ServiceDefs.json
=> Updated menuPath in serviceDefs.

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
@GhanshyamRawat , @ranjeeetvimal
=> role-action for password update without login api

data/pb/common-masters/Designation.json
=> renamed to camelcase

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> actions added for employee v2

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> roleactions added for v2

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> roleactions added for CITIZEN and employee/_search

data/pb/RAINMAKER-PGR/ServiceDefs.json
Updating data based on the sheet categories sheet as on 18/04/2018 (latest).
=> Updated service categories

data/pb/PropertyTax/ConstructionSubType.json, data/pb/PropertyTax/ConstructionType.json, data/pb/PropertyTax/OccupancyType.json, data/pb/PropertyTax/OwnerShipCategory.json, data/pb/PropertyTax/PropertySubType.json, data/pb/PropertyTax/PropertyType.json, data/pb/PropertyTax/SubOwnerShipCategory.json, data/pb/PropertyTax/UsageCategoryDetail.json, data/pb/PropertyTax/UsageCategoryMajor.json, data/pb/PropertyTax/UsageCategoryMinor.json, data/pb/PropertyTax/UsageCategorySubMinor.json, data/testtenant/PropertyTax/ConstructionSubType.json, data/testtenant/PropertyTax/ConstructionType.json, data/testtenant/PropertyTax/OccupancyType.json, data/testtenant/PropertyTax/OwnerShipCategory.json, data/testtenant/PropertyTax/PropertySubType.json, data/testtenant/PropertyTax/PropertyType.json, data/testtenant/PropertyTax/SubOwnerShipCategory.json, data/testtenant/PropertyTax/UsageCategoryDetail.json, data/testtenant/PropertyTax/UsageCategoryMajor.json, data/testtenant/PropertyTax/UsageCategoryMinor.json, data/testtenant/PropertyTax/UsageCategorySubMinor.json
=> pt data added to dev branch

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> pt-services-v2 actions added

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RoleActions added for pt-services-v2

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> csr role added for user profile update

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Added url as url for menutree links

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> AccessControl added for TL

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
@GhanshyamRawat 
@kaviyarasan1993
=> Role Actions for TL

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
TL registry id also adjusted to match current sequence
@GhanshyamRawat
=> action-test added for TL getbill

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> roleaction added for TL getbill

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> fetch bill added

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> role actions added for 1962

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> citizen added for billingSlab search

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Added action-test for TL-Report

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Added TL report role-action for employee

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
1714 - W&S Dashboard for EMPLOYEE
1715-1720 - TL Reports for EMPLOYEE
=> Added W&S Dashboard, TL reports for EMPLOYEE

data/pb/PropertyTax/Interest.json
=> dummy slabs added to test pro-rata interest logic

data/pb/PropertyTax/Penalty.json
=> added extra slab for testing

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> added action-test for workflow

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> added role-action for workflow

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> added workflow businessService api's

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RoleActions for businessService api in wf

punjab-data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Added Receipts Workflow url for the collection module.
=> ACCESSCONTROL-ACTIONS-TEST: Add Access control

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added new role actions for the collections receipt workflow.
@tarunlalwani
=> ACCESSCONTROL-ROLEACTIONS: Add role actions

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
@tarunlalwani please verify the request.
=> Add access control action for receipts workflow

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
@tarunlalwani please verify the request.
=> Update role actions for receipt workflow

data/pb/ACCESSCONTROL-ROLES/roles.json
=> changed "rolecode" to "code"

punjab-data/pb/ACCESSCONTROL-ROLES/roles.json
added a new role for TL workflow
=> updated role for TL

data/pb/ACCESSCONTROL-ROLES/roles.json
=> added tl document verifier

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> added employee role for TL billingslab search

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> added businessService search in workflow for citizen

data/pb/amritsar/BillingService/BusinessService.json, data/pb/amritsar/BillingService/TaxHeadMaster.json, data/pb/amritsar/BillingService/TaxPeriod.json
@GhanshyamRawat 
test data for billing service
=> billing service test data added for amritsar

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Please map this action to role whoever needs a workflow.
=> added new action for workflow

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> UI Role actions for TL employees

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Added egov-apportion-service API

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Added roleaction for apportion service

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> changed the apportion context path

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Reverts egovernments/egov-mdms-data#160
=> Revert "changed the apportion context path"

data/pb/amritsar/BillingService/TaxHeadMaster.json
=> Added advance taxHeads for PT and TL

data/pb/amritsar/BillingService/TaxHeadMaster.json
=> Added all PT taxHeads

data/pb/egf-master/FinancialYear.json
=> Added TL financialYears

data/pb/TradeLicense/ApplicationType.json
=> Add ApplicationType for TL

data/pb/amritsar/BillingService/TaxHeadMaster.json
=> PT interest taxHead added

data/pb/amritsar/BillingService/TaxHeadMaster.json
=> Added decimal credit and debit taxheads for PT

data/pb/amritsar/BillingService/TaxPeriod.json
@nithindv 
Added TL taxPeriod to test the integration with new Billing and collection service
=> Added TL taxPeriods

data/pb/amritsar/BillingService/TaxHeadMaster.json
@nithindv 
Added TL_ROUNDOFF taxhead to test the integration with the new billing and collection service
=> Added TL_ROUNDOFF taxHead

data/pb/PropertyTax/Interest.json
Changed starting day format from dd/MM to dd/MM/yyyy to avoid interpretation based on financial year
@tarunlalwani
=> added year in starting day

data/pb/amritsar/BillingService/TaxHeadMaster.json
=> Added PT_ROUNDOFF taxHead

data/pb/amritsar/BillingService/TaxHeadMaster.json
=> Corrected Purpose for PT_ADVANCE_CARRYFORWARD.

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> corrected calculate endpoint for pt

data/pb/nawanshahr/BillingService/BusinessService.json, data/pb/nawanshahr/BillingService/TaxHeadMaster.json, data/pb/nawanshahr/BillingService/TaxPeriod.json
=> added billing service data for nawanshahr

data/pb/amritsar/BillingService/TaxPeriod.json
=> Added entry for 2019-20

data/pb/egf-master/FinancialYear.json
=> Added 2019-20 for PT

data/pb/nawanshahr/BillingService/TaxPeriod.json
=> Added tax periods for 2019-20

data/pb/amritsar/BillingService/TaxPeriod.json
=> Added 2019-20 tax period for TL

data/pb/PropertyTax/FireCess.json
=> Updated fireCess to include dynamic rates

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
update role actions for NOC users
=> update role actions for NOC users

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
updated role action for noc users
=> updated role action for noc users

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
updated firenoc card to Noc employees.
=> update firenoc card role action

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
have added deduction rtgs action.
=> Adding remittence rtgs assignment role action mapping

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added logout role action for CSR
=> Added logout role action for CSR

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added Card actions to TL Doc and Field Inspector
=> Added Card actions to TL Doc and Field Inspector

data/pb/PropertyTax/Rebate.json
=> Updated rebate date for testing

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> added collections V2 endpoints

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> added mappings for collection v2 APIs

data/pb/common-masters/IdFormat.json, master-config.json
=> Add IDGen format MDMS

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
disabled assess the property and renamed the search property
=> Property menu action change

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Added _calculate of tl-calculate

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Added endpoints of config for locality search
=> added searcher endpoints

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Adding action for BPA to integrate.
=> Adding Action for BPA

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Adding roleaction mapping for BPA
Please review and merge asap, we need to BPA integrated into dashboard.
=> Adding roleaction mapping for BPA

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
fixing url - egov-bpa/search is correct url
=> fixing url - egov-bpa/search is correct url

data/pb/BPA/DocTypeMapping.json, data/pb/BillingService/BusinessService.json, data/pb/BillingService/TaxHeadMaster.json, data/pb/BillingService/TaxPeriod.json, data/pb/common-masters/IdFormat.json
Billing service realated master data.
=> Bpa services

data/pb/BPA/CalculationType.json
=> Added Sanction Fee For all

data/pb/ws-services-masters/billingPeriod.json
=> demand geneartion date added in billing period json of water services json

data/pb/sw-services-calculation/Interest.json, data/pb/sw-services-calculation/Penalty.json, data/pb/sw-services-calculation/billingPeriod.json, data/pb/ws-services-calculation/Interest.json, data/pb/ws-services-calculation/Penalty.json, data/pb/ws-services-masters/billingPeriod.json
jsons for water and sewerage updated for demand expiry date so that penaly and rebate can be applied
=> Ws mdms tarent

data/pb/BPA/OccupancyType.json, data/pb/BPA/SubOccupancyType.json, data/pb/BPA/Usages.json, master-config.json
added the occupancy and sub occupancy and usages to mdms data.
=> added the occupancy and sub occupancy and usages to mdms data.

data/pb/BPA/DocTypeMapping.json
=> doctype changes in the mdms data

data/pb/BPA/DocTypeMapping.json, data/pb/common-masters/DocumentType.json
Field inspection change in the code.
=> Simple change in the Field inspection.

data/pb/BPA/CheckList.json
=> Adding the required MDMS data to checklist

data/pb/amritsar/PropertyTax/Documents.json
=> updated document file in pt

data/pb/PropertyTax/ReasonForTransfer.json
added reason for transfer json
=> added reason for transfer json

data/pb/ACCESSCONTROL-ROLES/roles.json, data/pb/common-masters/CronJobAPIConfig.json
update TL cronjob and System user role
=> update TL cronjob and System user role

data/pb/common-masters/CronJobAPIConfig.json
=> disabled expiry cronjob

data/pb/TradeLicense/Penalty.json
Create Penalty.json for TL Renewal
=> Create Penalty.json for TL Renewal

data/pb/TradeLicense/Rebate.json
Create Rebate.json for TL Renewal
=> Create Rebate.json for TL Renewal

data/pb/PropertyTax/UsageCategory.json
Added usage categories for all combinations
=> Added usage categories for all combinations

data/pb/PropertyTax/OwnerShipCategory.json
added different ownership categories
=> added different ownership categories

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added remittance collection report action test mapping.
Added surrender cheque report action test mapping too because someone has removed the earlier added action.
=> Adding remittance roleaction mapping

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Code changes related to locality in employee inbox.
=> Code changes related to locality.

data/pb/StakeholderRegistraition/TradeTypetoRoleMapping.json
Stakeholder registration changes.
=> Code change in the stakeholder registration.

data/pb/common-masters/CronJobAPIConfig.json
Added context path in the WS-Service URL.. For testing purpose, so disabled the active flag in TL-Service
=> Updating URL for WS-Service

data/pb/common-masters/uiCommonPay.json
added bpa configuration in ui commonpay.
=> added bpa configuration in ui commonpay.

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
updated action test.json, changed endpoint urls for bpa services
=> BPA refactoring

data/pb/common-masters/uiCommonPay.json
=> bpareg common pay changes

data/pb/BPA/OccupancyType.json, data/pb/BPA/SubOccupancyType.json
MDMS change for occupancy and suboccupany data mapping with EDCR codes.
=> Phanikiran wtt egov patch 1

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/BPA/ServiceType.json
=> added new bpa urls

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> adding landInfo url actions

data/pb/BPA/CalculationType.json, data/pb/BPA/CheckList.json, data/pb/BPA/DocTypeMapping.json
=> calculation type for oc

data/pb/BillingService/BusinessService.json, data/pb/BillingService/TaxHeadMaster.json, data/pb/BillingService/TaxPeriod.json
=> added OC business Services

data/pb/ws-services-masters/waterSource.json
Added an object without minor type for testing purpose
=> Added object for testing purpose

data/pb/tenant/footer.json
Earlier disclaimer data is added only for amritsar, now added the same data for jalandhar also
=> Added disclaimerdata for jalandhar tenant

data/pb/BPA/CalculationType.json
changed the OC calculation type
=> changed the OC calculation type

data/pb/BPA/CalculationType.json
oc low sanction fee reference removed
=> oc low sanction fee reference removed

data/pb/BPA/CalculationType.json
removed the sanction for oc low application
=> removed the sanction for oc low application

data/pb/BPA/DocTypeMapping.json
added order to the doctype mapping
=> added order to the doctype mapping

data/pb/ws-services-masters/ApplicationType.json
Added ApplicationType.json which holds the list of W&S application type possible in the system.
=> WOR-330 Added new configuration - ApplicationType.json

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
chaning  the land service url in action-test
=> chaning  the land service url in action-test

data/pb/BPA/DocTypeMapping.json
added documents for all the missing states
=> added documents for all the missing states

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added role action for MDMS Menu items .
=> WOR-360 - Update roleactions.json

data/pb/BPA/DocTypeMapping.json
adding allow config to documentType mapping which will allow to upload docs other wise do not
=> adding allow config to documentType mapping

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
added bpa noc search url and roles
=> added bpa noc search url and roles

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> added display name in noc

master-config.json
master-config update for NOC module mdmds configs
=> master-config update for NOC module mdmds configs

data/pb/NOC/NocType.json
added nocUser role to the NocType
=> added nocUser role to the NocType

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
locality api access to noc servcies
=> locality api access to noc servcies

data/pb/NOC/NocType.json
updating the noc workflwo codes to resolve conflict with fireNoc module
=> updating the noc workflwow codes

data/pb/ws-services-masters/ModifyConnectionDocuments.json
… for Modify Water / Sewerage connection.
provides list of documents which needs to be collected when applying for Modify Water / Sewerage connection.
=> RAIN-1335: Required document configurations update for modify WS connections

data/pb/ws-services-masters/ApplicationType.json
provides different type of applications
=> RAIN-1335: Updated ApplicationType.json for different types of Applications

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> changed noc path

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
OAP-632
Adding worflow and locality access to the new NOC user roles Airport and FIRE noc user
=> OAP-632 Adding worflow and locality access to the new NOC user roles Airport and FIRE noc user

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> noc path change

data/pb/BPA/NocTypeMapping.json
changing the nocTrigger State from citizen_approval to Document_Verification pending in QA to test
=> changing the nocTrigger State

data/pb/RAINMAKER-PGR/ServiceDefs.json
Changing departments to test with existing employees
=> RAIN-1355: Updated departments in PGR

data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json, data/pg/BPA/DocTypeMapping.json, data/pg/BPA/NocTypeMapping.json, data/pg/NOC/DocumentTypeMapping.json, data/pg/NOC/NocType.json, master-config.json
MDMS merge to UAT for bpa-services and noc-services
=> MDMS merge to UAT for bpa-services and noc-services

data/pg/ACCESSCONTROL-ROLES/roles.json
added FIRENOC and AIPROT Roles
=> OAP-634 - Update roles.json

data/pg/common-masters/IdFormat.json
OAP-634 Idformat for noc application number missing
=> OAP-634 Idformat for noc application number missing

data/pb/FinanceService/AccountCodeTemplate.json
FINANCE-125:mdms data for accountcode template in contractor
=> FINANCE-125:mdms data for accountcode template in contractor

data/pg/citya/FinanceService/OnlineInstrumentType.json
FINANCE-131 Receipt types are added
=> FINANCE-131 Receipt types are added

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
RAIN-1379 - Removed unused PGR Reports and corrected URL
=> RAIN-1379 - Removed unused PGR Reports

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1379 - Removed ULBReport access from Employee
=> RAIN-1379 - Removed ULBReport access from Employee

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1528 :: Added Description report to GRO, LME
=> RAIN-1528 :: Added Description report to GRO, LME

data/pg/ACCESSCONTROL-ROLES/roles.json
RAIN-1605 - updating UAT mdms for September Release
=> RAIN-1605 - updating UAT mdms for Sep Release

data/pg/common-masters/StateInfo.json
RAIN-1605 - Enabled localization change option in UAT
=> RAIN-1605 - Enabled localization change option

data/pg/DataSecurity/DecryptionABAC.json
RAIN-1605 - Report issue changes
=> RAIN-1605 - Report issue changes

data/pg/ws-services-masters/ModifyConnectionDocuments.json
RAIN-1605 - Added modify connection Documents
=> RAIN-1605 - Added modify connection Documents

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1605: update pt role actions
=> RAIN-1605: update pt role actions

data/pg/ws-services-masters/ApplicationType.json
RAIN-1605 - Added application type dropdown for WS
=> RAIN-1605 - Added application type dropdown for WS

data/pb/tenant/tenants.json
Reverts egovernments/egov-mdms-data#1282
=> Revert "Update ddr name for testing purpose"

data/pg/common-masters/uiCommonPay.json
RAIN-1660 - Arrears taxhead changes for Common pay screen in UAT
=> RAIN-1660 - Arrears taxhead changes for Common pay

data/pg/common-masters/IdFormat.json
RAIN-1379 - Updated the one time fee format for WS
=> RAIN-1379 - Updated the one time fee format for WS

data/pb/BillAmendment/documentObj.json, data/pb/common-masters/DocumentType.json
RAIN-1674 (MDMS Config Creation for documents)
=> RAIN-1674 (MDMS Config Creation for documents)

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json, data/pb/BillAmendment/DemandRevisionBasis.json
RAIN-1674 (Bill Amendment UI: MDMS Config Creation and Integration demand Revision  basis)
=> RAIN-1674 (Bill Amendment UI: MDMS Config Creation and Integration demand Revision  basis)

data/pb/common-masters/DocumentType.json
RAIN-1660 - MDMS Config Creation for documents
=> RAIN-1660 - MDMS Config Creation for documents

data/pb/BillAmendment/documentObj.json
RAIN-1660 - Document Required Screen Creation - changed the mdms required documents response as per PRD
=> RAIN-1660 - Document for Bill amendment changes

data/pb/common-masters/TablePaginationOptions.json
=> 1723 (TablePaginationOptions)

data/pb/common-masters/TablePaginationOptions.json
RAIN-1723 (TablePaginationOptions)
=> RAIN-1723 (TablePaginationOptions)

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1660 - Removed pagination access from PT approver to test workflow search error
=> RAIN-1660 - Removed pagination access from PTA

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1660 - Given inbox access to emp to test workflow search error
=> RAIN-1660-inbox access to emp-test workflow error

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1660-count API access to emp-test workflow
=> RAIN-1660-count API access to emp-test workflow

data/pb/PropertyTax/MutationDocuments.json
RAIN-1660 - Added mutation reason-special category
=> RAIN-1660 - Added mutation reason-special category

data/pb/tenant/tenants.json
RAIN-1660 - Adding pincode data to tenants
=> RAIN-1660 - Adding pincode data to tenants

data/pb/BillAmendment/documentObj.json
added allowed format ,max file size to one time settlement in documentObj in bill amendment
=> RAIN-1660-allowed format,max filesize -documentObj

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-1679 (Receipt download)

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-1660 Payment search changes for Firenoc user
=> RAIN-1660 Payment search changes for Firenoc user

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
FSM-74 (added) FSM Create and Search api added and citizen access
=> FSM-74 (added) FSM Create and Search api added and citizen access

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Updated PGR navigationURL. RAIN-1995 : Updated PGR Urls
=> Updated PGR navigationURL

data/pb/PropertyTax/PTWorkflow.json
=> Enabled for PT Create and disabled PT W&S.

data/pb/PropertyTax/PTWorkflow.json
Reverts egovernments/egov-mdms-data#1383
=> Revert "Enabled for PT Create and disabled PT W&S."

data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
PGR UI V2 navigation URL changes for ids : 1557, 1559, 1775, 1805, 1814, 1925, 1927, 1555
=> RAIN-1660 : PGR UI V2 navigation URL changes

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Removed Duplicate ID number in Actiontest.json
=> Removed Duplicate ID number

data/pb/BillingService/BusinessService.json
Bill Amend enabled Water and sewerage Applications for searching
=> Bill Amend enabled Water and sewerage Applications

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Added ids 2054,2055,2056,2057,2058 for FSM
=> FSM related changes for Vendor Vehicle

data/pb/FSM/PitType.json
Added PitType json file for FSM
=> Added PitType json file for FSM

data/pb/FSM/VehicleType.json
Added VehicleType Json file for FSM
=> Added VehicleType Json file for FSM

data/pb/BillingService/TaxHeadMaster.json
=> Added FSM roundoff for FSM

data/pb/FSM/PropertyType.json
Added a new file PropertyType.json for FSM
=> Added a new file PropertyType.json for FSM

data/pb/FSM/ApplicationChannel.json
Updated Application json file for FSM
=> Updated Application json file for FSM

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Updated Action for Create , Search,Update for Bill Amendment
=> Updated Action for Create , Search,Update

data/pb/FSM/PitType.json
Updated Pit Type json file for FSM
=> Updated Pit Type json file for FSM

data/pb/common-masters/IdFormat.json
=> FSM-107 fsm receipt id

data/pb/common-masters/IdFormat.json
=> Update Id Format json for FSM

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Updated role action collector for FSM 2058 - Editor, FSM collector and citizen
=> Updated role action collector for FSM

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Updated role actions for FSM id:706 -Search Demand and 2058 - FSM Application Charge Payment Search
706 - FSM ADMIN, FSM DSO, FSM DRIVER, CITIZEN, FSM EDITOR, FSM COLLECTOR, FSM ADMIN, DSO
2058 - FSM ADMIN, FSM DSO, FSM DRIVER, FSM VIEW EMP
=> Updated role actions id 706 & 2058 for FSM

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Updated role actions id:706 for FSM
706 : FSM CREATOR EMP
=> Updated role actions id:706 for FSM

data/pb/BillAmendment/DemandRevisionBasis.json
Changed the Updated Code in demandrevisionbasis.json
=> Changed the Updated Code in demandrevisionbasis

data/pb/FSM/PropertyType.json
RAIN-2164 added property type details
=> RAIN-2164 added property type details

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
RAIN-2164 added audit search details
=> RAIN-2164 added audit search details

data/pb/Vehicle/VehicleMakeModel.json
RAIN - 2164 Created vehicle details
=> RAIN - 2164 Created vehicle json file

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 added vehicle audit roles
=> RAIN-2164 added vehicle audit roles

data/pb/PropertyTax/PTWorkflow.json
Reverts egovernments/egov-mdms-data#1490
=> Revert "Enabled PT.CREATEWITHWNS for testing purpose"

data/pb/BillingService/TaxHeadMaster.json
Updated w&s tax heads for Bill Amendment
=> RAIN 2164: Updated w&s tax heads for Bill Amendment

data/pb/BillingService/BusinessService.json
Reverts egovernments/egov-mdms-data#1500
=> Revert "Rain : 2164 Enabling Bill Amendment"

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> RAIN-2164 Added Billing Slab

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 Added Billing Slab Role actions
=> RAIN-2164 Added Billing Slab Role actions

data/pb/Vehicle/VehicleMakeModel.json
RAIN-2164 Added Vehicle MakeModel Details
=> RAIN-2164 Added Vehicle MakeModel Details

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 - change password access given to PGR

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
RAIN-2164 Added Vehicle trip and FSM Estimate details
=> RAIN-2164 Added Vehicle trip and FSM Estimate details

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 Added role actions details
=> RAIN-2164 Added role actions details

data/pb/common-masters/IdFormat.json
RAIN-2164 Added Vehicle Trip Application Number format
=> RAIN-2164 Added Vehicle Trip Application Number format

data/pb/FSM/Config.json
RAIN-2164 Added config.json file
=> RAIN-2164 Added config.json file

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN - 2164 added employee search access to

data/pb/BillingService/TaxHeadMaster.json
=> RAIN-2164 - Updatedfor Bill Amendment changes

data/pb/tenant/citymodule.json
=> RAIN-2164 - Enabled Amritsar and Nawanshahr for

data/pb/BillingService/TaxHeadMaster.json
=> RAIN-2164 - Reverting changes done for Bill

data/pb/FSM/Slum.json
=> RAIN-2164 Added Slum Details

data/pb/FSM/Config.json
RAIN-2164 Updated Config Changes
=> RAIN-2164 Updated Config Changes

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 Updated Role Actions Details
=> RAIN-2164 Updated Role Actions Details

data/pb/tenant/footer.json
RAIN-2164 Added Receipt Footer changes
=> RAIN-2164 Added Receipt Footer changes

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 Added Role Action details
=> RAIN-2164 Added Role Action

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 Added Role Action Details
=> RAIN-2164 Added Role Action Details

data/pb/FSM/FSTPPlantInfo.json, data/pb/FSM/PropertyType.json
min and max amount for PropertyUsage
FSTP Plant information details as mdms added
=> Phanikiran wtt egov patch 15

data/pb/FSM/FSTPPlantInfo.json
RAIN-2164 Added FSTP Plantinfo
=> RAIN-2164 Added FSTP Plantinfo

data/pb/FSM/FSTPPlantInfo.json
RAIN-2164 Updated FSTP Plant Details
=> RAIN-2164 Updated FSTP Plant Details

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Added id 2082 and 2083 for FSM card
=> RAIN-2164 Added id 2082 and 2083 for FSM card

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2164 mapped action id 2082 and 2083 to roles for FSM card
=> RAIN-2164 mapped action id 2082 & 2083 to roles

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Removed extra , from the role action mapping
=> RAIN-2164 Removed extra ,

data/pb/FSM/PropertyType.json
Updated minAmount and maxAmount for Commercial and Residential
=> RAIN-2164 Updated minAmount and maxAmount

data/pb/FSM/PropertyType.json
Updated Institutional min and max amount
"minAmount":"1000",
"maxAmount":"3000"
=> RAIN-2164 Updated Institutional min and max amount

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
removed id 2046 employee role mapping
=> RAIN-2164 removed id 2046 employee role mapping

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added action ids 1729, 1730,  1743, 2027, 2046 to DSO
=> RAIN-2164 Added action ids to DSO

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added id 2046 to All FSM roles
FSM_DRIVER
FSM_COLLECTOR
FSM_DSO
FSM_ADMIN
FSM_EDITOR_EMP
FSM_CREATOR_EMP
FSM_EMP_FSTPO
FSM_VIEW_EMP
=> RAIN-2164 Added id 2046 to All FSM roles

data/pb/FSM/CheckList.json
=> RAIN-2164 Updated code : SPILLAGE

data/pb/common-masters/IdFormat.json
RAIN-2164 Updated IdFormat changes
=> RAIN-2164 Updated IdFormat changes

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added role action for id 2083 to 2091 for FSM
=> RAIN-2164 Added role action for id 2083 to 2091

data/pb/common-masters/IdFormat.json
ApplicationNumber FSM and vehicle
=> ApplicationNumber FSM and vehicle

data/pb/common-masters/IdFormat.json
Updated idnames - vehiclelog and fsm 
"idname": "vehiclelog.aplnumber",
"idname": "fsm.aplnumber",
=> RAIN-2164 Updated idnames - vehiclelog and fsm

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 Updated code CITIZEN id 2057

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 Removed duplicate FSM card for

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 - FSM create access given to

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 - Collect payment action added to

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 Added vendor search access to FSM

data/pg/tenant/tenants.json
=> RAIN-2164 Changed citya email id to be generic

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2164 REmoved PGR access from Employee

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
PGR employees and Complaint card to PGR LME
=> RAIN-2164 Added business service search access to

data/pb/tenant/footer.json
removing second disclarimer in the receipt
=> removing second disclarimer in the receipt

data/pb/tenant/footer.json
RAIN-2164 Updated footer.json details
=> RAIN-2164 Updated footer.json details

data/pg/tenant/tenants.json
Updated domain url  for city B
=> RAIN-2164 Updated domain url  for city B

data/pg/tenant/footer.json
=> RAIN-2164 Removed second line in disclaimer

data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> RAIN-2164 FSM added a New Icon for inbox

master-config.json
=> mdms at tenantLevel

data/pg/FSM/Slum.json
Updated slum data for JLC476 to JLC487
=> RAIN-2164 Updated slum data for JLC476 to JLC487

data/pb/amritsar/FSM/Slum.json
Updated slum changes to ULB level
=> RAIN-2164 Updated slum changes to ULB level

data/pg/FSM/PropertyType.json
Updated min max Amount of Property type
=> RAIN-2164 Updated min max Amount of Property type

data/pb/FSM/CancelReason.json
RAIN-2164 Added Cancel Reasons
=> RAIN-2164 Added Cancel Reasons

data/pb/FSM/DeclineReason.json
RAIN-2164 Added Decline Reason
=> RAIN-2164 Added Decline Reason

data/pb/FSM/ReassignReason.json
RAIN-2164 Added Reassign Reason
=> RAIN-2164 Added Reassign Reason

data/pb/FSM/RejectionReason.json
RAIN-2164 Added Rejection Reason
=> RAIN-2164 Added Rejection Reason

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2346 Added role actions details
=> RAIN-2346 Added role actions details

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Reverts egovernments/egov-mdms-data#1669
=> Revert "RAIN-2346 Added role actions details"

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2346 Added role action details
=> RAIN-2346 Added role action details

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2364 Added role actions for FSM
=> RAIN-2364 Added role actions for FSM

data/pb/DIGIT-UI/RoleStatusMapping.json
RAIN-2346 Added Role Status Mapping Details
=> RAIN-2346 Added Role Status Mapping Details

data/pg/balasore/egov-location/boundary-data.json
Odissa ward and zone dummy data added for balasore
=> Odissa ward and zone dummy data added for balasore

data/pg/balasore/egov-location/boundary-data.json
ODISSA adding admin boundary data for balasore
=> ODISSA adding admin boundary data for balasore

data/pg/tenant/tenants.json
=> Corrected code for Balasore and added 2 more ulbs

data/pg/balasore/FSM/Slum.json
=> balasore Slum update

data/pg/balasore/FSM/Slum.json
=> balasore slum json modified

data/pb/DIGIT-UI/RoleStatusMapping.json
RAIN-2346 Updated Role Status Mapping Details
=> RAIN-2346 Updated Role Status Mapping Details

data/pb/FSM/PostFieldsConfig.json
RAIN-2346 Added Post fields config details
=> RAIN-2346 Added Post fields config details

data/pb/FSM/CommonFieldsConfig.json
RAIN-2346 Added Common Fields Config Details
=> RAIN-2346 Added Common Fields Config Details

data/pb/FSM/PreFieldsConfig.json
RAIN-2346 Added Pre fields config details
=> RAIN-2346 Added Pre fields config details

data/pb/tenant/tenants.json
Updated email id for amritsar 
From cmcasr@gmail.com
to  cmcasrcmcasrcmcasrcmcasrcmcasrcmcasr@gmail.com
=> RAIN-2164 Updated email id for amritsar

data/pb/FSM/CommonFieldsConfig.json
RAIN-2346 Updated Common fields config details
=> RAIN-2346 Updated Common fields config details

data/pg/DIGIT-UI/RoleStatusMapping.json
=> RAIN-2164 Created new json file

data/pg/FSM/CommonFieldsConfig.json
Created new CommonFieldsConfig.json file
=> RAIN-2164 Created new CommonFieldsConfig.json file

data/pg/FSM/PostFieldsConfig.json
created new PostFieldsConfig.json file
=> RAIN-2164 created new PostFieldsConfig.json file

data/pg/FSM/PreFieldsConfig.json
Created new PreFieldsConfig.json file
=> RAIN-2164 Created new PreFieldsConfig.json file

data/pg/FSM/CommonFieldsConfig.json
isMandatory to false for Pit details
=> RAIN-2164 isMandatory to false for Pit details

data/pb/PropertyTax/RentalDetails.json
RAIN-2346 Removed hardcoded value rental details for PT 2.0 changes
=> RAIN-2346 Removed hardcoded value rental details

data/pb/common-masters/uiCommonPay.json
Reverts egovernments/egov-mdms-data#1734
=> Revert "RAIN :: 2346 Updated eChallan Common Pay"

data/pb/DIGIT-UI/RoleStatusMapping.json
RAIN-2346 Updated Role Status Details
=> RAIN-2346 Updated Role Status Details

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> FSM DSS ACCESS

data/pb/DIGIT-UI/RoleStatusMapping.json
RAIN-2346 Updated Role Status Mapping
=> RAIN-2346 Updated Role Status Mapping

data/pg/BillingService/TaxPeriod.json
=> RAIN-2346 Removed duplicate entry for

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Business service search access added

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
TL Doc verifier and Field Inspector
=> RAIN-2346 added tl billing slab search access to

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Added business service access

data/pb/PropertyTax/PTApplication.json
=> RAIN-2346 PT edit action in case of

data/pb/common-masters/uiCommonPay.json
RAIN-2346 Updated CommonPay Details
=> RAIN-2346 Updated CommonPay Details

data/pb/FSM/CommonFieldsConfig.json
RAIN-2346 Updated Common fields details
=> RAIN-2346 Updated Common fields details

data/pg/common-masters/uiCommonPay.json
RAIN-2346 Updated ui Common Pay details
=> RAIN-2346 Updated ui Common Pay details

data/pg/FSM/CommonFieldsConfig.json
RAIN-2346 Updated FSM Common fields deatils
=> RAIN-2346 Updated FSM Common fields deatils

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Added firenoc receipt access

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Added business service search access to

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Added employee search access to PT and

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Added payment search access to PT and

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2346 Create access mapped with FSM creator

data/pb/PropertyTax/Documents.json
=> RAIN-2346 PT Documents required updated

data/pb/egf-master/FinancialYear.json
=> RAIN-2346 Updated starting date for 21-22

data/pb/common-masters/uiCommonPay.json
=> RAIN-2346 Added PDF module for All

data/pb/mCollect/applicationStatus.json
RAIN-2524 added status for search filter
=> RAIN-2524 added status for search filter

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2523 Add mCollect Card for new framework
=>  RAIN-2523 Add mCollect Card for new framework

data/pb/FSM/FSTPPlantInfo.json
updating plantinfo for derabassi, phagwara and other tenants
=> updating plantinfo for derabassi, phagwara and other tenants

data/pb/tenant/tenants.json
changing ddrname for FSM DSS DEMO
=> changing ddrname for FSM DSS DEMO

data/pg/common-masters/StateInfo.json
=> RAIN-2768 Updated Hindi Locale label

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Updated the Roleaction for PGR_LME   
id 1752
/egov-hrms/employees/_search
=> RAIN-2768 Updated the Roleaction for PGR_LME

data/pb/common-masters/CancelCurrentBillReasons.json, data/pb/common-masters/uiCommonPay.json
RAIN-2485 added current bill cancel reasons and cancelbill config in common pay
=> RAIN-2485 added current bill cancel reasons and cancelbill config in common pay

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2768 Added reopen access for CSR

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added Request update role action for CSR
=> RAIN-2768 Added Request update role action for CSR

data/pb/Workflow/AutoEscalation.json
Updated business service to test Auto escalation
=> RAIN-2768 Updated business service

data/pb/Workflow/AutoEscalation.json
Updated business service name  for Auto Escalation testing
=> RAIN-2768 Updated business service name

data/pb/Workflow/AutoEscalation.json
Added business service for Auto escalation
=> RAIN-2768 Added business service

data/pb/common-masters/GenderType.json
Common Masters added a Gender Type mdms
=> RAIN-2768 Common Masters added a Gender Type mdms

data/pb/Workflow/AutoEscalation.json
Updated buisness sla for Auto escalation
=> RAIN-2768 Updated buisness sla

data/pb/common-masters/CronJobAPIConfig.json
Added entry in cron job api config file
=> RAIN-2768 Added entry in cron job api config file

data/pb/Workflow/AutoEscalation.json
Updated sla time and removed dummy business service data
=> RAIN-2768 Updated sla time and removed dummy data

data/pb/PropertyTax/PropertySubType.json, data/pb/PropertyTax/SubOwnerShipCategory.json, data/pb/PropertyTax/UsageCategoryDetail.json, data/pb/PropertyTax/UsageCategoryMajor.json, data/pb/PropertyTax/UsageCategoryMinor.json, data/pb/PropertyTax/UsageCategorySubMinor.json
Reverts egovernments/egov-mdms-data#1948
=> Revert "RAIN-2768 Removed unused files fot Property Tax"

data/pb/RAINMAKER-PGR/ServiceDefs.json
=> RAIN-2768 Enabled service defs for PGR

data/pb/Workflow/AutoEscalation.json
Updated sla value to test AutoEscalation
=> RAIN-2768 Updated sla value to test AutoEscalation

data/pb/Workflow/AutoEscalation.json
Added dummy business service for Auto escalation
=> RAIN-2768 Added dummy business service

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2768 Added role action for LME

data/pb/Workflow/AutoEscalation.json
Added Reject action to citizen to test Auto escalation
=> RAIN-2768 Added Reject action to citizen

data/pb/Workflow/BusinessServiceMasterConfig.json
Updated isStatelevel value for Auto escalation
=> RAIN-2768 Updated isStatelevel value

data/pb/Workflow/BusinessServiceMasterConfig.json
Reverted is Statelevel value for Auto Escalation
=> RAIN-2768 Reverted is Statelevel value

data/pb/Workflow/AutoEscalation.json
=> RAIN-2768 Updated sla for TL

data/pb/Workflow/BusinessServiceMasterConfig.json
Added business service for AE to test
=> RAIN-2768 Added business service for sla

data/pb/RAINMAKER-PGR/ServiceDefs.json
RAIN-2768 : Ontologies changes for PGR
=> RAIN-2768 : Ontologies changes for PGR

data/pb/BPA/OccupancyType.json
RAIN-2768 : Ontologies changes 1 for OBPAS
=> RAIN-2768 : Ontologies changes 1 for OBPAS

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2768 Updated missing role for TL

data/pg/common-masters/uiCommonConstants.json
RAIN-2768 Added fsm & ulb-fsm in uiCommonConstants.json file
=> RAIN-2768 Added fsm & ulb-fsm in uiCommonConstants

data/pb/BPA/OccupancyType.json
=> RAIN-2768: Corrected code

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-2768 Added PT card on home page

data/pb/BillingService/BusinessService.json
RAIN-2768 Updated mCollect ontologies 1
=> RAIN-2768 Updated mCollect ontologies 1

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-2768 Updated roleactions for BPA
=> RAIN-2768 Updated roleactions for BPA

data/pb/common-masters/CronJobAPIConfig.json
=> RAIN-3414 Updated Cron job for FSM

data/pb/PropertyTax/UpdateNumber.json
=> RAIN-3414 :: PT Update number , Updated Pattern

data/pb/FSM/PeriodicService.json
Updated Periodic Application timelimit
=> RAIN-3414 Updated Periodic Application timelimit

data/pb/BPA/homePageUrlLinks.json
RAIN-3256 Added links for home page for different flows
=> RAIN-3256 Added links for home page for different flows

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Updated egov searcher for Bill Genie
=> RAIN-3414 Updated egov searcher for Bill Genie

data/pb/BPA/homePageUrlLinks.json
=> RAIN-3414  Added links for home page for

data/pb/common-masters/IdFormat.json
Added id format for document create
=> RAIN-3414 Added id format for document create

data/pb/common-masters/IdFormat.json
=> RAIN-3414 Added idformat for survey

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added roleaction to citizen for survey
=> RAIN-3414 Added roleaction to citizen for survey

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-3414 Updated roleaction for survey

data/pb/common-masters/CronJobAPIConfig.json
Updated cron job value to test TL auto expired status
=> RAIN-3414 Updated cron job value to test TL

data/pb/TradeLicense/CommonFieldsConfig.json
Added TL Create/edit/renew config in mdms
=> Added TL Create/edit/renew config in mdms

data/pb/TradeLicense/CommonFieldsConfig.json
TL config Changed to Withoutlabel to withoutLabel
=> TL config Changed to Withoutlabel to withoutLabel

data/pb/PropertyTax/CommonFieldsConfig.json
Changes for state level customization
Should be reverted once automation task completed or if any issues found during R2.6 release task testing.
=> RAIN-3474 : Changes for state level customization

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Provided citizen role to document search API
=> RAIN-3414 Provided citizen role to document search

data/pb/TradeLicense/CommonFieldsConfig.json
Added TL Create/edit/renew config in mdms
=> RAIN-3414 Added TL Create/edit/renew config in mdms

data/pb/DocumentUploader/DocumentUploader.json
Added Document category to other tenants
=> RAIN-3414 Added Document category to other tenants

data/pb/tenant/citymodule.json
Updated active true for TL and BPA
=> RAIN-3414 Updated active true for TL and BPA

data/pg/FSM/CommonFieldsConfig.JSON, data/pg/FSM/PostFieldsConfig.json, data/pg/FSM/PreFieldsConfig.json
=> Added missing ui configs

data/pb/Channel/channelList.json
updated config for notification channel:
Approve and Send to architect flow
=> RAIN-3414 updated config for notification channel

data/pb/Channel/channelList.json
changes for notification channel
Apply, approve, pay, skip payment, send back to citizen, forward, revocate, reject, adhoc
=> RAIN-3414 Updated mdms config changes for notification channel

data/pb/PropertyTax/CommonFieldsConfig.json
RAIN-3414 Changes for state level customization
"vacant": "map" (line no 211)
"PT_COMMON_NO": "map", (line no 354)
"nextStep": "map", (line no 372)
=> RAIN-3414 Changes for state level customization

data/pb/BPA/BuildingPermitConfig.json, data/pb/BPA/EdcrConfig.json, data/pb/BPA/InspectionReportConfig.json, data/pb/BPA/OCBuildingPermitConfig.json, data/pb/BPA/OCEdcrConfig.json, data/pb/BPA/StakeholderConfig.json
RAIN-3814 added bpa configs for new ui screens
=> RAIN-3814 added bpa configs for new ui screens

data/pb/Channel/channelList.json
Added actions for bpa stakeholder regestration
=> RAIN-3414 mdms changes - stakeholder registration

data/pg/FinanceService/AccountCodeTemplate.json
RAIN-3414 Adding AccountCodeTemplate.json
Adding a new file for Finance module
=> RAIN-3414 Adding AccountCodeTemplate.json

data/pb/StakeholderRegistraition/TradeTypetoRoleMapping.json
RAIN-4419 OBPS : Documents Required screen options is not as per the requirement.
=> RAIN-4419 OBPS : Documents Required screen options is not as per the requirement.

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-3414 Correcting action id for UC_EMP for BulkPDF
=> RAIN-3414 Correcting action id for UC_EMP

data/pb/Channel/channelList.json
Added notifications for NewTL, EditRenewal and DirectRenewal
=> RAIN-3414 Added notifications for TL

data/pb/BillingService/BusinessService.json
Updated duplicate value for BA
=> RAIN-3414 Updated duplicate value for BA

data/pb/tenant/citymodule.json
=> RAIN-4583 Enabled WS Module

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-4624 OBPS: Not able to logout from airport NOC login.
=> RAIN-4624 OBPS: Not able to logout from airport NOC login.

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
FIRE_NOC_APPROVER, AIRPORT_AUTHORITY_APPROVER, BPA_VERIFIER, BPA_FIELD_INSPECTOR, BPA_NOC_VERIFIER, BPA_APPROVER
=> RAIN-3414 roleactions added

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
RAIN-4663 - added role actions
=> RAIN-4663 - added role actions

data/pg/common-masters/IdFormat.json
added idgen format for stakeholder registration application number and license number into UAT
=> RAIN-3414 added idgen format for bpareg

data/pg/common-masters/IdFormat.json
corrected city name to "PG" in format based on UAT environment
=> RAIN-3414 corrected format for bpareg

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-4654 added role actions

data/pb/tenant/citymodule.json
Updated http to https for banner img
=> RAIN-3414 Updated http to https for banner img

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added role action for BPA CE for downloading receipt
=> RAIN-3414 Added role action for BPA CE

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json, data/pb/common-masters/uiCommonConstants.json
=> Dev firenoc - RAIN-4675

data/pb/NOC/NOCBusinessServiceRoleMaping.json
=> RAIN-4948 added the NOCBussinessServiceRoleMapping data 

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added filestore role action for DSS admin
=> RAIN-4911 Added filestore role action for admin

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json, data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json, data/pb/common-masters/uiCommonConstants.json
Added role actions for firenoc RAIN-4675
=> Added role actions for firenoc RAIN-4675

data/pb/BPA/BPAAppicationMapping.json
RAIN-4938: added stakeholder roles for applcation and service types selection in BPA
=> RAIN-4938: added stakeholder roles for applcation and service types selection in BPA

data/pb/TradeLicense/ReminderPeriods.json
Updated the reminder period to test TL
=> RAIN-4911 Updated the reminder period to test TL

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-4911 Added role for NATADMIN

data/pb/DIGIT-UI/HelpText.json
config changes for configurable max result
=> RAIN-4911 PT Config changes

data/pb/PropertyTax/CommonFieldsConfig.json
Removing unwanted config in commonfield
=> RAIN-4911 Removing unwanted config in commonfield

data/pb/tenant/nationalInfo.json
changing the state code to stateName
=> changing the state code to stateName

data/pb/amritsar/TradeLicense/ReminderPeriods.json
Updated the reminder period to test TL
=> RAIN-4911-Updated the reminder period to test TL

data/pb/FSM/PaymentType.json
Added PaymentType json file for user story SAN-849 - Add citizen's choice for payment
=> Added PaymentType json file for user story SAN-849 - Add citizen's choice for payment

data/pb/Vehicle/VehicleOwner.json
…for vehicle
Added VehicleOwner.json file for story SAN-689 - Add owner attribute for vehicle
=> Added VehicleOwner.json file 

data/pb/Channel/channelList.json
Added paid action for PT notifications
=> RAIN-4911 Added paid action fro PT

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-4911 Added role action for Survey

data/pb/Vendor/AgencyType.json, data/pb/Vendor/PaymentPreference.json
SAN - 841 - Adding vendor details for FSM
=> SAN - 841 - Adding vendor details for FSM

data/pb/FSM/PreFieldsConfig.json
Adding for payment preferences
=> Adding for payment preferences

data/pb/DIGIT-UI/RoleStatusMapping.json
Added component for adding status in DSO inbox status
=> Added component for adding status in DSO inbox status

master-config.json
Added PaymentType and PaymentPreference for FSM
=> Added PaymentType and PaymentPreference for FSM

data/pb/Channel/channelList.json
Added Failure action for PT Notification
=> RAIN-4911 Added Failure action for PT Notification

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Updated for SAN-803 story

data/pb/FSM/Config.json
SAN-854 Override trip number of trips
=> SAN-854 Override trip number of trips

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> SAN-803 - Status update issue

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-4911 Updated roleaction for NDSS

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> RAIN-4911 Updated roleacton for DSS

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Updated NDSS Navigation URL to new ui
=> RAIN-4911 Updated NDSS Navigation URL to new ui

data/pg/Vehicle/FSTPORejectionReason.json
=> Create FSTPORejectionReason.json for decline functionality from FSTPO

data/pg/FSM/PaymentType.json
=> Create PaymentType.json for adding pre pay and post pay workflow

data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Update roleactions.json for timeline changes on adding waiting for disposal and disposed status

data/pg/FSM/PreFieldsConfig.json
=> Update PreFieldsConfig.json for adding paymentpreference

master-config.json
=> Update master-config.json for adding payment preference functionality 

data/pg/Vehicle/VehicleOwner.json
=> Create VehicleOwner.json for create and update vehicle api validation

data/pg/tenant/nationalInfo.json
adding madhyapreadesh to the states list
=> adding madhyapreadesh to the states list

data/pg/tenant/nationalInfo.json
added new states for UAT state data loading for landing page
=> added new states for UAT state data loading for landing page

data/pg/TradeLicense/ReminderPeriods.json
Updated the reminder period to test TL
=> Rain 4911-Updated the reminder period to test TL

data/pg/citya/TradeLicense/ReminderPeriods
Updated the reminder period to test TL
=> Rain 4911-Updated the reminder period to test TL UAT

data/pb/egf-master/FinancialYear.json
Updated order of Financial year
=> RAIN-4911 Updated order of Financial year

data/pg/egf-master/FinancialYear.json
Corrected tenant ID for Financial year
=> RAIN-4911 Corrected tenant ID for Financial year

data/pg/egf-master/FinancialYear.json
RAIN-4911 Added financial year for WS
=> RAIN-4911 Added financial year for WS

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Update roleactions to have a access for mutation estimate on citizen side
=> RAIN-4911 Added roleaction for mutation estimate

data/pb/common-masters/uiHomePage.json.txt
=> FSM- UI - loading issue fix

data/pb/FSM/ReceivedPaymentType.json
FSM V1.1.1 - SAN-889, 890 and 983 - Adding ReceivedPaymentType/json
=> FSM V1.1.1 - SAN-889, 890 and 983 - Adding ReceivedPaymentType/json

data/pb/TradeLicense/CommonFieldsConfig.json
=> RAIN-6821 Updated config for TL

data/pb/BillingService/BusinessService.json
BND Download receipt config updated type to adhoc
=> RAIN-6821 BND Download receipt config updated

data/pb/TradeLicense/CommonFieldsConfig.json
Removed HTML validation for TL-PT particular fields
=> RAIN-6821 Removed HTML validation for TL-PT

data/pg/TradeLicense/CommonFieldsConfig.json
Removed HTML validations from TL-PT few fields
=> RAIN-6821 Removed HTML validations from TL-PT

data/pb/TradeLicense/CommonFieldsConfig.json
=> RAIN-6821 PT TL Added Owner type doc

data/pb/BillingService/TaxHeadMaster.json
Enabled isBillamend value for adhoc penalty and rebate
=> RAIN-6821 BA Enabled value for adhoc penalty and rebate

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added role action mapping for WS Inbox
=> RAIN-6821 Added role action mapping for WS Inbox

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-7093 Add role action mapping for fire noc user
=> RAIN-7093 Add role action mapping for fire noc user

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Added role action mapping for BPA fire noc user
=> RAIN-6821 Added role action mapping for BPA

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
RAIN-7093 OBPS :: Improvements in Application Details screen
=> RAIN-7093 OBPS :: Improvements in Application Details screen

data/pb/DataSecurity/SecurityPolicy.json
Reverts egovernments/egov-mdms-data#2541
=> Revert "Revert "RAIN - 6821 Created SecurityPolicy.json file""

data/pb/DataSecurity/PatternData.json
Reverts egovernments/egov-mdms-data#2542
=> Revert "Revert "RAIN-6821 Created PatternData.Json file""

data/pb/tenant/citymodule.json
=> RAIN-6821 Added Mohali Tenant for DSS

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
->Added appropriate roles for /ws-calculator/meterConnection/_search  api
=> RAIN-7257 W&S :: Employee :: Consumption details added by Counter Employee are not displayed on DV, FI and AP consumption details screen

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
WS- Added roleaction for Consumption details to show in DV, FI and AP
=> RAIN-6821 WS- Added roleaction for Consumption

data/pb/BillingService/BusinessService.json
=> RAIN-6821 Added minAmountPayable flag

data/pb/BillingService/BusinessService.json
=> RAIN-6821 Added minAmountPayable for SW

data/pb/DataSecurity/SecurityPolicy.json
Reverts egovernments/egov-mdms-data#2574
=> Revert "RAIN-6821 Updated security policy.json file"

data/pb/DataSecurity/SecurityPolicy.json
Reverts egovernments/egov-mdms-data#2575
=> Revert "RAIN-6821 Updated pattern ID for userself model"

data/pb/Channel/channelList.json
=> Rain-6821: Actions is added

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Role action mappings are added
=> Rain-6821: Role action mappings are added

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Rain-6821 :Role action mappings is added

data/pb/DataSecurity/SecurityPolicy.json
Added Privacy for WS_CEMP User
=> RAIN-6821 : Added Privacy for WS_CEMP User

data/pb/DataSecurity/SecurityPolicy.json
UI Privacy Changes Test integration for pt module
=> RAIN-6821:UI Privacy Changes Test integration for pt module

data/pb/DataSecurity/SecurityPolicy.json
Privacy Added for PII fields of PT
=> RAIN-6821 : Privacy Added for PII fields of PT

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Rain-6821:Added the action for Firenoc

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Rain-6821:Added the role for firenoc

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Added the action for birth and death
=> Rain-6821: Added the action for birth and death

data/pb/DataSecurity/SecurityPolicy.json
Removed mask for name and Added Mask for Gender & Guardian
=> RAIN-6821 : WS :Privacy Added mask for Gender and Guardian

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Role action mapping get the home button
=> Rain-6821: Role action mapping get the home button

data/pg/tenant/nationalInfo.json
=> Added Punjab other 164 ULB's

data/pb/DataSecurity/SecurityPolicy.json
=> Shubhang qa

data/pb/common-masters/HowItWorks
=> Rain-6821: HowItWorks added

data/pb/common-masters/faqs.json
=> Rain-6821-Faqs added

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Rain-6821: Pt how it works and Pt faqs

data/pb/ACCESSCONTROL-ROLEACTIONS/roleactions.json
=> Rain-6821: Updated role actions

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> SM-511-Driver tab changes 

data/pb/ws-services-masters/ApplicationType.json
Adding Disconnect WS to Application type
=> UM-464 Adding Disconnect WS to Application type

data/pb/common-masters/IdFormat.json
Added IDGen formats for WS Disconnection
=> UM-464 Added IDGen formats for WS Disconnection

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> Rain-6821: TL FAQs added in module card

data/pb/FSM/PreFieldsConfig.json
- Removed Payment config from Application details
=> SM-497 : FSM V1.2 : ULB New application +(modify application) 

data/pb/common-masters/StaticData.json
=> UM-464-Added missing static data

data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> UM-463: FAQs added

data/pb/tenant/citymodule.json
UM-4179 UI/UX Audit :: W&S :: Employee :: Audit review Issues in w&s Employee side
=> UM-4179 UI/UX Audit :: W&S :: Employee :: Audit review Issues in w&s Employee side

data/pb/tenant/citymodule.json
=> UM-464 Bill Amendment Inbox change

data/pb/FSM/CommonFieldsConfig.json
=> FSM V1.2.2 : SM-497 - ULB New application 

data/pb/DataSecurity/SecurityPolicy.json
Removed the config for PT_CEMP Role
=> UM-464: Removed the config for PT_CEMP Role

data/pb/common-masters/faqs.json
Splitted the faq into two parts
=> UM-464:Splitted the faq into two parts

data/pb/tenant/tenants.json
=> UM-464: Added the contact no

data/pb/TradeLicense/CommonFieldsConfig.json
TL added trade details screen in the flow
=> UM-464: TL added trade details screen in the flow

data/pb/DataSecurity/SecurityPolicy.json
Added Citizen Role for Privacy
=> UM-464 :: Added Citizen Role for Privacy

data/pb/DataSecurity/SecurityPolicy.json
Added Citizen Role for WNS Privacy
=> UM-464 :: Added Citizen Role for WNS Privacy

data/pb/TradeLicense/CommonFieldsConfig.json
TL UI Object placement fix for TL screen
=> UM-464: TL UI Object placement fix for TL screen

data/pb/DataSecurity/SecurityPolicy.json
Added WNS Employees Roles for Privacy
=> UM-464 :: Added WNS Employees Roles for Privacy

data/pb/DataSecurity/SecurityPolicy.json
Reverts egovernments/egov-mdms-data#2765
=> Revert "UM-464 :: Added WNS Employees Roles for Privacy"

data/pb/DataSecurity/SecurityPolicy.json
Added WNS  Employees Roles for Privacy
=> UM-464 :: Added WNS  Employees Roles for Privacy

data/pb/inbox-dss/ElasticSearchQueries.json
updated query parameter in the ElasticSearchQueries
=> DPG-610 changes in the ElasticSearchQueries

data/pb/inbox-dss/ElasticSearchQueries.json
Updated the placeholders- parameters
=> DPG-764: Updated elastic search query

data/pg/common-masters/IdFormat.json
=> UM-464 : changed cb to ulb code

data/pb/common-masters/uiHomePage.json
Citizen Home Screen services card
=> UM-4419::Citizen Home Screen services card

data/pb/ws-services-masters/WSActivationConfig.json, data/pb/ws-services-masters/WSCreateConfig.json, data/pb/ws-services-masters/WSDisconnectionConfig.json
UM-4809 UI : W&S Module enable all form configs to be a MDMS config
=> UM-4809 UI : W&S Module enable all form configs to be a MDMS config

data/pb/ws-services-masters/WSDisconnectionConfig.json
W&S Module form configs to be a MDMS config
=> UM-4809 UI : W&S Module form configs to be a MDMS config

data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> UM-464: Updated the url

data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
=> UM-464:Updated the url

data/pg/ws-services-masters/DisconnectionDocuments.json
=> um-4763 :: module name change

data/pg/TradeLicense/CommonFieldsConfig.json
updated CommonFieldsConfig.json as per qa file to resole the issue
=> UM-5188,UM-5190 : update tl-CommonFieldsConfig.json

data/pb/Channel/channelList.json
Pt notification missing config added
=> Pt Notification missing config added

data/pg/Channel/ChannelList.json
Added pt notification for SENDBACKFROMFI and SENDBACKFROMAP
=> PT Notification config updated

data/pg/ws-services-calculation/SMSReceiver.json
=> changed mobile number, email id
